version: "3.7"

services:
  web:
    build: .
    environment:
      NODE_ENV:
      MONGODB_URI: mongodb://root:fxeYkC56yJ67quRMcWz3qy@mongodb:27017/
    command: sh -c "until nc -z -w 2 mongodb 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done"
    depends_on:
      - mongodb
    ports:
      - "4000:4000"

  mongodb:
    image: mongo:4.4
    user: mongodb
    environment:
      - MONGO_INITDB_DATABASE=admin // This is important
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=fxeYkC56yJ67quRMcWz3qy
    ports:
      - "27017:27017"
